name: Test SSH Connection

on:
  push:
    branches: [ main ] 

jobs:
  test-ssh:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          echo "Testing SSH connection..."
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "SSH connection successful!"