name: Test SSH Connection

on:
  push:
    branches: [ main ] 

jobs:
  test-ssh:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key_path: ~/.ssh/deploy_key
        port: 22
        script: |
          echo "Testing SSH connection..."
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "SSH connection successful!"