name: Deploy palbin-tools to Production

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Debug SSH Key
      run: |
        echo "Checking SSH key format..."
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | grep -q "BEGIN OPENSSH PRIVATE KEY" && echo "Key format looks correct" || echo "Key format might be incorrect"
        echo "Key length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l) lines"
      
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        envs: |
          GITHUB_SHA
          GITHUB_REF
        script: |
          echo "Starting deployment..."
          cd /opt/apps/palbin-tools
          git pull origin main
          npm ci --production
          npm run build
          pm2 restart palbin-tools