name: Deploy palbin-tools to Production

on:
  push:
    branches: [ main ] 

jobs:
  test-ssh:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Test SSH Connection
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
          echo "Testing SSH connection..."
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"
          echo "SSH connection successful!"
        '