name: Deploy to Production

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    name: Deploy palbin-tools
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    
    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v3
    #   with:
    #     ref: main
    
    # - name: Create GitHub deployment
    #   uses: chrnorm/deployment-action@v2
    #   id: deployment
    #   with:
    #     token: '${{ github.token }}'
    #     environment: production
    
    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '23'
        
    # - name: Install dependencies
    #   run: npm ci
      
    # - name: Build application
    #   run: npm run build
      
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 137
        script: |
          echo "Starting deployment..."
          # Load environment variables and paths
          source ~/.bashrc
          source ~/.profile
          cd /opt/apps/palbin-tools
          git pull
          npm ci --production
          npm run build
          pm2 restart palbin-tools
          echo "Deployment completed successfully!"
          
    # - name: Update deployment status (success)
    #   if: success()
    #   uses: chrnorm/deployment-status@v2
    #   with:
    #     token: '${{ github.token }}'
    #     state: 'success'
    #     deployment-id: ${{ steps.deployment.outputs.deployment_id }}
    # 
    # - name: Update deployment status (failure)
    #   if: failure()
    #   uses: chrnorm/deployment-status@v2
    #   with:
    #     token: '${{ github.token }}'
    #     state: 'failure'
    #     deployment-id: ${{ steps.deployment.outputs.deployment_id }}