name: Test SSH Connection

on:
  push:
    branches: [ main ] 

jobs:
  test-ssh:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Setup SSH Key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/deploy_key
        chmod 600 /home/runner/.ssh/deploy_key
        echo "Key format:"
        ssh-keygen -l -f /home/runner/.ssh/deploy_key || echo "Key format issue"
        echo "Key content first line:"
        head -n 1 /home/runner/.ssh/deploy_key
        
    - name: Test SSH Connection
      run: |
        ssh -vvv -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no -p 137 ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'echo "SSH connection successful!"'